### ISSUE TITLE
Doesn't work with parameterized routing & Apollo

### ISSUE THREAD

**Issue by adamsoffer** [scaleapi/data-prefetch-link#7]
Data prefetching no longer works using the latest next apollo example. I imagine it has something to do with the introduction of `_app.js`. Has anyone managed to get it working with the apollo example?

**Comment by Enalmada** [comment]
I tried it with the "with-apollo-auth" example and it worked for me (was using next 7.0.2).  I saw a console log in the getInitialProps of a new linked page off of index page fire when I was on my index page. Make sure you are trying it in production mode as this seems to be disabled in dev mode.

**Comment by adamsoffer** [comment]
Hmm, I tried it in production mode, but still not working. I’m using parameterized  routing with next-routes. Maybe it doesn’t play well with that lib.

**Comment by adamsoffer** [comment]
I think it just doesn't work with parameterized routing in general. If anyone has been able to get data prefetching to work with parameterized routing I'd love to know how you did it!

**Comment by Enalmada** [comment]
That is unfortunate as I figure lots of real users will have parameterized routing eventually.  Change your issue title and hopefully someone will experience will notice it and let us know if that is a bug or fundamental limitation.
